#!/usr/bin/env python3
"""Install Worklight from this checkout and manage its shell/tmux integrations.

Run through mise: `mise run setup [-- -y|--dry-run|...]`.

Nothing is applied without confirmation, nothing outside a marked block is
touched, and no git pull, pin upgrade, sudo or database change ever happens
here.
"""

from __future__ import annotations

import argparse
import datetime as dt
import difflib
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

CHECKOUT = Path(__file__).resolve().parent.parent
BEGIN = "# >>> worklight >>>"
END = "# <<< worklight <<<"
TMUX_BEGIN = "# >>> worklight >>>"
TMUX_END = "# <<< worklight <<<"


class SetupError(Exception):
    """A problem the user has to resolve explicitly."""


# --- locations -----------------------------------------------------------


def cargo_bin_dir(env: dict[str, str]) -> Path:
    cargo_home = env.get("CARGO_HOME")
    if cargo_home:
        return Path(cargo_home).expanduser() / "bin"
    return Path(env.get("HOME", "~")).expanduser() / ".cargo" / "bin"


def config_dir(env: dict[str, str]) -> Path:
    base = env.get("XDG_CONFIG_HOME")
    if base:
        return Path(base).expanduser() / "worklight"
    return Path(env.get("HOME", "~")).expanduser() / ".config" / "worklight"


def zshrc_path(env: dict[str, str], override: str | None) -> Path:
    if override:
        return Path(override).expanduser()
    zdotdir = env.get("ZDOTDIR")
    home = Path(env.get("HOME", "~")).expanduser()
    if zdotdir:
        candidate = Path(zdotdir).expanduser() / ".zshrc"
        other = home / ".zshrc"
        if other.exists() and not candidate.exists():
            raise SetupError(
                f"ZDOTDIR is {zdotdir} but only {other} exists; "
                "pass --zshrc to say which file to edit"
            )
        return candidate
    return home / ".zshrc"


def tmux_conf_path(env: dict[str, str], override: str | None) -> Path:
    if override:
        return Path(override).expanduser()
    home = Path(env.get("HOME", "~")).expanduser()
    xdg = env.get("XDG_CONFIG_HOME")
    candidates = [
        (Path(xdg).expanduser() / "tmux" / "tmux.conf") if xdg else (home / ".config" / "tmux" / "tmux.conf"),
        home / ".tmux.conf",
    ]
    existing = [path for path in candidates if path.exists()]
    if len(existing) > 1:
        listed = ", ".join(str(path) for path in existing)
        raise SetupError(
            f"several tmux configurations exist ({listed}); pass --tmux-conf to choose one"
        )
    if existing:
        return existing[0]
    return candidates[0]


# --- generated integrations ---------------------------------------------


def zsh_integration(bin_dir: Path) -> str:
    quoted = shlex.quote(str(bin_dir))
    return f"""# Generated by worklight setup. Edits here are overwritten.
# Adds the worklight binary directory to PATH, once.
# No command tracking hooks are installed.
worklight_bin={quoted}
case ":$PATH:" in
  *":$worklight_bin:"*) ;;
  *) PATH="$worklight_bin:$PATH" ;;
esac
export PATH
unset worklight_bin
"""


def tmux_integration(binary: Path) -> str:
    # #{q:...} makes tmux shell-quote the client name, and the binary path is
    # quoted here, so neither can break out of the popup command.
    quoted = shlex.quote(str(binary))
    return f"""# Generated by worklight setup. Edits here are overwritten.
# prefix + Space opens the worklight panel in a popup, focusing only the
# client that opened it.
bind-key Space display-popup -E -w 80% -h 70% \\
    "WORKLIGHT_TMUX_CLIENT=#{{q:client_name}} {quoted} panel"
"""


def loader_block(target: str) -> str:
    return f'{BEGIN}\nsource {shlex.quote(target)}\n{END}\n'


def tmux_loader_block(target: str) -> str:
    return f'{TMUX_BEGIN}\nsource-file -q {shlex.quote(target)}\n{TMUX_END}\n'


def apply_block(existing: str, block: str, begin: str, end: str, path: Path) -> str:
    """Replace the marked block, preserving everything around it."""
    starts = [i for i, line in enumerate(existing.splitlines()) if line.strip() == begin]
    ends = [i for i, line in enumerate(existing.splitlines()) if line.strip() == end]
    if len(starts) > 1 or len(ends) > 1:
        raise SetupError(
            f"{path} contains more than one worklight block; remove the extras first"
        )
    if bool(starts) != bool(ends):
        raise SetupError(
            f"{path} has an unterminated worklight block; fix it by hand first"
        )
    if not starts:
        prefix = existing
        if prefix and not prefix.endswith("\n"):
            prefix += "\n"
        return prefix + block
    lines = existing.splitlines(keepends=True)
    if ends[0] < starts[0]:
        raise SetupError(f"{path} has a worklight block whose markers are out of order")
    return "".join(lines[: starts[0]]) + block + "".join(lines[ends[0] + 1 :])


def binding_conflict(existing: str, path: Path) -> None:
    """Refuse to silently take over an existing prefix + Space binding."""
    inside = False
    for line_number, line in enumerate(existing.splitlines(), start=1):
        stripped = line.strip()
        if stripped == TMUX_BEGIN:
            inside = True
            continue
        if stripped == TMUX_END:
            inside = False
            continue
        if inside or not stripped or stripped.startswith("#"):
            continue
        try:
            words = shlex.split(stripped, comments=True, posix=True)
        except ValueError as error:
            raise SetupError(
                f"cannot parse {path}:{line_number} while checking tmux bindings: {error}"
            ) from error
        if not words or words[0] not in ("bind", "bind-key"):
            continue

        table = "prefix"
        index = 1
        while index < len(words) and words[index].startswith("-"):
            option = words[index]
            index += 1
            if "n" in option[1:]:
                table = "root"
            if option in ("-T", "-N"):
                if index >= len(words):
                    raise SetupError(
                        f"cannot parse incomplete tmux binding at {path}:{line_number}"
                    )
                value = words[index]
                index += 1
                if option == "-T":
                    table = value
        if index >= len(words):
            raise SetupError(f"cannot parse incomplete tmux binding at {path}:{line_number}")
        key = words[index]
        if table == "prefix" and (key == " " or key.casefold() == "space"):
            raise SetupError(
                f"{path} already binds prefix + Space ({stripped!r}); "
                "remove it or pass --tmux-conf to use another file"
            )


# --- change planning -----------------------------------------------------


class Change:
    def __init__(self, path: Path, contents: str) -> None:
        self.path = path
        self.contents = contents
        self.before = path.read_text() if path.exists() else ""

    @property
    def changed(self) -> bool:
        return self.before != self.contents

    def diff(self) -> str:
        return "".join(
            difflib.unified_diff(
                self.before.splitlines(keepends=True),
                self.contents.splitlines(keepends=True),
                fromfile=f"a/{self.path}",
                tofile=f"b/{self.path}",
            )
        )

    def apply(self, stamp: str) -> list[str]:
        notes = []
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if self.path.exists():
            backup = self.path.with_name(f"{self.path.name}.worklight-{stamp}.bak")
            shutil.copy2(self.path, backup)
            notes.append(f"backed up {self.path} to {backup}")
        self.path.write_text(self.contents)
        notes.append(f"wrote {self.path}")
        return notes


def plan(args: argparse.Namespace, env: dict[str, str]) -> list[Change]:
    bin_dir = cargo_bin_dir(env)
    conf = config_dir(env)
    zsh_file = conf / "integrations.zsh"
    tmux_file = conf / "integrations.tmux"

    zshrc = zshrc_path(env, args.zshrc)
    tmux_conf = tmux_conf_path(env, args.tmux_conf)
    tmux_existing = tmux_conf.read_text() if tmux_conf.exists() else ""
    binding_conflict(tmux_existing, tmux_conf)

    return [
        Change(zsh_file, zsh_integration(bin_dir)),
        Change(tmux_file, tmux_integration(bin_dir / "worklight")),
        Change(
            zshrc,
            apply_block(
                zshrc.read_text() if zshrc.exists() else "",
                loader_block(str(zsh_file)),
                BEGIN,
                END,
                zshrc,
            ),
        ),
        Change(
            tmux_conf,
            apply_block(
                tmux_existing,
                tmux_loader_block(str(tmux_file)),
                TMUX_BEGIN,
                TMUX_END,
                tmux_conf,
            ),
        ),
    ]


# --- build and install ---------------------------------------------------


def build_and_install(env: dict[str, str]) -> None:
    """Build first, then install, so a broken build changes nothing."""
    subprocess.run(
        ["cargo", "build", "--release"], cwd=CHECKOUT, env=env, check=True
    )
    subprocess.run(
        ["cargo", "install", "--path", str(CHECKOUT), "--force"],
        cwd=CHECKOUT,
        env=env,
        check=True,
    )


def reload_tmux(socket: str | None, tmux_file: Path) -> str:
    """Load only the generated file, never the whole user configuration."""
    command = ["tmux"]
    if socket:
        command += ["-S", socket]
    command += ["source-file", str(tmux_file)]
    try:
        result = subprocess.run(command, capture_output=True, text=True)
    except OSError as error:
        raise SetupError(f"could not run tmux to load {tmux_file}: {error}") from error
    if result.returncode != 0:
        detail = result.stderr.strip() or f"tmux exited with status {result.returncode}"
        raise SetupError(
            f"could not load {tmux_file} into the tmux server: {detail}"
        )
    return f"loaded {tmux_file} into the running tmux server"


# --- entry point ---------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-y", "--yes", action="store_true", help="accept ordinary confirmations")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="show the planned changes and exit; overrides --yes",
    )
    parser.add_argument("--zshrc", help="the zsh configuration to edit")
    parser.add_argument("--tmux-conf", help="the tmux configuration to edit")
    parser.add_argument(
        "--reload-tmux",
        nargs="?",
        const="",
        metavar="SOCKET",
        help="also load the generated tmux integration into a running server",
    )
    args = parser.parse_args(argv)
    env = dict(os.environ)

    try:
        changes = plan(args, env)
    except SetupError as error:
        print(f"setup: {error}", file=sys.stderr)
        return 1

    pending = [change for change in changes if change.changed]
    binary = cargo_bin_dir(env) / "worklight"
    print(f"worklight setup from {CHECKOUT}")
    print(f"  binary: {binary}")
    if not pending:
        print("  configuration is already up to date")
    for change in pending:
        print()
        print(change.diff() or f"--- {change.path} (new file)")

    if args.dry_run:
        # A preview builds nothing, installs nothing and creates no directory.
        print("\ndry run: nothing was built, installed or written")
        return 0

    if not args.yes:
        if not sys.stdin.isatty():
            print(
                "setup: refusing to change anything without confirmation; pass -y",
                file=sys.stderr,
            )
            return 1
        answer = input("\nApply these changes and install the binary? [y/N] ").strip().lower()
        if answer not in ("y", "yes"):
            print("setup: nothing was changed")
            return 1

    notes: list[str] = []
    try:
        build_and_install(env)
        notes.append(f"installed {binary}")
    except subprocess.CalledProcessError as error:
        print(
            f"setup: build or install failed ({error}); no configuration was changed",
            file=sys.stderr,
        )
        return 1

    stamp = dt.datetime.now().strftime("%Y%m%d%H%M%S")
    applied: list[Change] = []
    for change in pending:
        try:
            notes.extend(change.apply(stamp))
            applied.append(change)
        except OSError as error:
            print(f"setup: could not write {change.path}: {error}", file=sys.stderr)
            print(
                "setup: partially applied. Files already written are listed above and "
                "each has a .worklight-*.bak beside it; restore those to undo.",
                file=sys.stderr,
            )
            for note in notes:
                print(f"  {note}", file=sys.stderr)
            return 1

    if args.reload_tmux is not None:
        try:
            notes.append(
                reload_tmux(
                    args.reload_tmux or None,
                    config_dir(env) / "integrations.tmux",
                )
            )
        except SetupError as error:
            print(f"setup: {error}", file=sys.stderr)
            print(
                "setup: binary installation and configuration writes completed, "
                "but the requested live tmux reload did not",
                file=sys.stderr,
            )
            for note in notes:
                print(f"  {note}", file=sys.stderr)
            return 1

    for note in notes:
        print(f"  {note}")
    print("  start a new zsh session to pick up the shell changes")
    if args.reload_tmux is None and any(
        change.path.name.startswith("tmux") or change.path.suffix == ".conf"
        for change in applied
    ):
        print("  tmux: re-run with --reload-tmux to load the binding into a running server")
    return 0


if __name__ == "__main__":
    sys.exit(main())
